server:
  port: 8761


spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      default-filters:
        - name: Retry
          args:
            retries: 15
            backoff:
              firstBackoff: 50ms
              maxBackoff: 500ms
        - name: TokenRelay
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true

  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: ${OAUTH2_ISSUER_URI:http://localhost:8180}/realms/${OAUTH2_REALM:var-realm}
        registration:
          keycloak:
            provider: keycloak
            clientId: ${OAUTH2_CLIENT_ID}
            clientSecret: ${OAUTH2_CLIENT_SECRET}
            scope:
              - openid
  endpoints:
    gateway:
      enabled: true
    web:
      exposure:
        include: '*'

logging:
  level:
    org:
      springframework:
        security: DEBUG