version: "3.9"

volumes:
  postgres-data:
  keycloak-data:

services:

  keycloak:
    image: quay.io/keycloak/keycloak
    container_name: keycloak
    command:
      - start-dev --import-realm
    volumes:
      - ./var-deployment/docker/keycloak:/opt/keycloak/data/import
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - '8180:8080'

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
