server:
  port: 8888

spring:
  application:
    name: discovery-service
  profiles:
    active: ${APP_PROFILE:dev}

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: ${DISCOVERY_SERVICE_URL:http://localhost:${server.port}/eureka/}

management:
  endpoints:
    web:
      exposure:
        include: '*'