global:
  scrape_interval: 2s


scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:9090' ]
  - job_name: eureka-discovery
    scrape_interval: 2s
    scrape_timeout: 2s
    metrics_path: /actuator/prometheus
    eureka_sd_configs:
      - server: http://host.docker.internal:9002/eureka
        refresh_interval: 2s
    relabel_configs:
      - source_labels: [ __meta_eureka_app_name ]
        target_label: application
      - source_labels: [ __meta_eureka_app_instance_metadata_metrics_path ]
        target_label: __metrics_path__
      - source_labels: [ __address__ ]
        target_label: instance
