server:
  port: 9001

spring:
  application:
    name: config-service
  profiles:
    active: ${APP_PROFILE:native}
  cloud:
    config:
      server:
        native:
          search-locations:
            - classpath:/config
          order: 2
        git:
          uri: https://github.com/volalm15/var
          search-paths: 'config/'
          order: 1
eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_SERVICE_URL:http://localhost:8888/eureka/}
  instance:
    lease-expiration-duration-in-seconds: ${DISCOVERY_LEASE_EXPIRATION:3}
    lease-renewal-interval-in-seconds: ${DISCOVERY_LEASE_RENEWAL:1}
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${random.value}

logging:
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"

info:
  system: Polar Bookshop

management:
  endpoints:
    web:
      exposure:
        include: configprops, env, health, heapdump, info, loggers, mappings, prometheus
  endpoint:
    health:
      show-details: always
      show-components: always
      probes:
        enabled: true
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true
  tracing:
    sampling:
      probability: 1.0
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
    tags:
      application: ${spring.application.name}