server:
  port: 8760

spring:
  application:
    name: config-service
  profiles:
    active: ${APP_PROFILE:native}
  cloud:
    config:
      server:
        native:
          search-locations:
            - classpath:/config
          order: 2
        git:
          uri: https://github.com/volalm15/var
          search-paths: 'config/'
          order: 1
eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_SERVICE_URL:http://localhost:8888/eureka/}
  instance:
    lease-expiration-duration-in-seconds: ${DISCOVERY_LEASE_EXPIRATION:3}
    lease-renewal-interval-in-seconds: ${DISCOVERY_LEASE_RENEWAL:1}
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${random.value}

management:
  endpoints:
    web:
      exposure:
        include: '*'