name: Build config-service
on:
  push:
    branches:
      - main
      - feature/*
  pull_request:
    branches:
      - main
      - feature/*

permissions:
  packages: write

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Run gradle build
        run: ./gradlew :config-service:bootJar

      - name: Publish jar artifact
        uses: actions/upload-artifact@v3
        with:
          path: config-service/build/libs/*.jar

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build docker image
        run: docker build --build-arg JAR_FILE=config-service/build/libs/*.jar -t ghcr.io/volalm15/config-service:latest -f config-service/Dockerfile .

      - name: Publish docker image
        run: |
          docker push ghcr.io/volalm15/config-service:latest
