name: Build data-service
on:
  push:
    branches: [ main ]
    paths:
      - "data-service/**"
  pull_request:
    branches: [ main ]
    paths:
      - "data-service/**"

permissions:
  packages: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run gradle build
        run: ./gradlew :data-service:bootJar

      - name: Publish jar artifact
        uses: actions/upload-artifact@v3
        with:
          path: data-service/build/libs/*.jar

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build docker image
        run: docker build --build-arg JAR_FILE=data-service/build/libs/*.jar -t ghcr.io/volalm15/data-service:latest -f data-service/Dockerfile .

      - name: Publish docker image
        run: |
          docker push ghcr.io/volalm15/data-service:latest
